### ISSUE TITLE
gopenpgp: cannot unlock keyring, no private key available

### ISSUE THREAD

**Issue by dmunao** [mssun/passforios#339]
Both Public and Secret keys were successfully imported via itunes but I cannot decrypt my store anymore. The app still prompts for secret key password while I am sure it is right. Testing on version 0.8 and ios 13.2.3

**Comment by dmtroyer** [comment]
I had the same issue and had to reinstall the application. Seems like maybe there were breaking changes in 0.8.0?

**Comment by bienchen** [comment]
Same here, could import both keys but can't decrypt. I keep getting the message: "Unable to decrypt. Invalid message or missing key to decrypt message.". I copy the secret key password from another password manager and on the host that works. Host I created my pass storage is MacOS with GnuPG 2.2.18, passforios is 0.8.0 (41), iOS is 13.2.3. Maybe that one is related to it? While the solution does not work anymore: https://emacs.stackexchange.com/questions/27841/unable-to-decrypt-gpg-file-using-emacs-but-command-line-gpg-works/27870

**Comment by mssun** [comment]
Hi all, I'm not sure if this is related with our recent update. If reinstalling the app can solve the issue, definitely caused by the upgrade.

**Comment by bienchen** [comment]
I did reinstall but this did not help.

**Comment by mssun** [comment]
This is wired. Let me check whether we have updated the pgp library first.

**Comment by mssun** [comment]
I found that there some changes on the gopgp library: https://github.com/mssun/passforios/commits/master/gopenpgp_build.sh

I suspect this issue is caused by the updated library. Can you tell me the encryption algorithm you are using right now?

**Comment by bienchen** [comment]
What would that be? I'm new to using GPG. I did generate my keys with "RSA and RSA", 4096 as keysize.

**Comment by dmunao** [comment]
I have successfully worked around the issue by importing the keys via plain text (ASCII) deleting the iTunes imported keys. The app is now working as expected

**Comment by dmunao** [comment]
> I found that there some changes on the gopgp library: https://github.com/mssun/passforios/commits/master/gopenpgp_build.sh
> 
> I suspect this issue is caused by the updated library. Can you tell me the encryption algorithm you are using right now?

I have generated my keys using RSA4096

**Comment by dmtroyer** [comment]
I found that I had to re-export my keys making sure to use the `-a` switch for ascii armored output which I had not originally done. I probably didn't need to reinstall the application after all.

**Comment by bienchen** [comment]
I used `-a` when creating the ASCII keys. Import via clipboard.

**Comment by bienchen** [comment]
What I did now: transfer my GPG keys from MacOS into Linux and decrypted my password file there with gpg. That works.

**Comment by bienchen** [comment]
I think I solved it. At least for me I fixed it. It may be the output format of the GPG version on my Mac, installed via homebrew: 2.2.18. After importing the key on Linux with GPG 2.0.22 I exported it and the private key in ASCII Armored is different. Sending the Linux-exported key to passforios allows me to decrypt my passwords!

**Comment by hyiltiz** [comment]
@bienchen Any idea if #456 is the same issue? I tried what you described but it did not solve the issue.

**Comment by bienchen** [comment]
Hm, not sure. For me it was a formatting error from different GPG versions. What sounds odd with #456 is that it worked for some users with passforios 0.9.0 and stopped working after upgrade. Maybe have a look at the gopenpgp versions used in 0.9.0 and after that.

**Comment by hyiltiz** [comment]
After `0.9.0` there was a version bump right after which mentioned using a new gopenpgp library. I am guessing it probably has something to do with that.
