### ISSUE TITLE
Entries added in the app won't be deleted, when deleted outside

### ISSUE THREAD

**Issue by nielsk** [mssun/passforios#60]
Create a new entry in the app and sync to your repo
Now on your computer delete or move the entry, sync again with git
Sync with the app and the entry still exists. In the case of a move to a folder, the entry will also exist in the folder now (so now you have it twice).

But syncing to the repo won't add the local entry again to the repo until you change something in the local entry.

**Comment by yishilin14** [comment]
Thanks for your report. It seems like the logic of file organization is not robust. Adding an entry where the "name" contains an non-existing folder name also crashes the app...

**Comment by yishilin14** [comment]
Fixed. The bug is triggered by flawed "git add/commit" implementation.

**Comment by nielsk** [comment]
works for me now as well

**Comment by nielsk** [comment]
Oops, sorry - it doesn't work for me in 0.2.1
The entries still exist after a sync and they are not in my repo anymore at that position

**Comment by nielsk** [comment]
Beware: when you created before this bug was fixed an entry and moved it on another computer via git mv; and do now a git pull on the other computer the entry will be deleted.
You have to edit the entry on the iOS-client and sync. Then sync on the computer. Then it gets pulled again. Then move it (pass mv bar foo/bar), sync again and then sync the iOS-client. Then the entry will be at the correct position again.
Luckily I created only a few entries on the iOS-client so far because that part is/was so buggy.

**Comment by yishilin14** [comment]
I am so sorry for the inconvenience.

We are trying our best to polish the logic, and we are short of hands now. To avoid similar problems, we suggest that you make sure that your repo looks like what you want at any time. For example, by syncing your updates timely. In case you feel that some bugs will probably mess up your repo, you may erase everything and clone a clean repo again. 

Thank you so much for your patience and valuable reports!
