### ISSUE TITLE
Crashes on iOS 10.3.1

### ISSUE THREAD

**Issue by steffen9000** [mssun/passforios#70]
Hi,

thanks for your great work on Pass for iOS.

I noticed a problem with the application on my iPhone 6 that was recently updated to iOS 10.3.1. After cloning my Pass data through SSH, the application instantly crashes and fails to start again unless deleted. I'm using password-based authentication for SSH and a self hosted, bare git repository (which was worked fine before).

I'm also using the latest TestFlight build.

**Comment by mssun** [comment]
I need to reproduce this crash later today. Thanks for your report.

In the meantime, I want to know if other authentication methods have the same issue.

From my side, https/password combination works well.

**Comment by mssun** [comment]
I tried from a new installation.

My repo is self hosted and bare git repo. I can clone the repo on the app by SSH and password methods.

Could you try it from a new installation? Sometimes, a TestFlight update will break internal data structure. You can try to Discard All Password Store Data in Advanced setting page.

**Comment by vonProteus** [comment]
have same problem
i use self hosted repo via ssh and rsa key (4096b)
i tried 2 times, removed app between attempts

[pass-2017-04-12-184248.ips.beta.txt](https://github.com/mssun/passforios/files/917294/pass-2017-04-12-184248.ips.beta.txt)
[pass-2017-04-12-184252.ips.beta.txt](https://github.com/mssun/passforios/files/917295/pass-2017-04-12-184252.ips.beta.txt)

hope it helps

**Comment by steffen9000** [comment]
Authenticating via SSH key produces the same problem for me. I also tried:

- deleting  the app and reinstalling through Testflight
- Discarding all Password Store data

Without success :(

**Comment by mssun** [comment]
@vonProteus @steffen9000 This is strange. Can you detail the format of your input git repo URL?

I use ssh://username@server/directory-to-repo/repo.git to test my bare repo. It works under both password and SSH key authentication methods.

I need to reproduce and investigate this issue.

**Comment by steffen9000** [comment]
My repo url is ssh://user@subdomain.domain:port/path/to/pass.git. I'm also using a rather long password (20+ chars).

My iPad on iOS 10.3 is fine though, everything works as expected. I'm hesitant to update to iOS 10.3.1 (because Pass might stop working :) ), but I guess I'll do it for science and report back.

**Comment by mssun** [comment]
@steffen9000 Are you using mater branch (origin/master)?

**Comment by vonProteus** [comment]
i use
ssh://git@gogs.server.name/vonProteus/passwords.git
and my password branch is called master

**Comment by steffen9000** [comment]
Yes, my password branch is origin/master as well.

**Comment by nnutter** [comment]
I just got invited to Pass for iOS today and believe I am affected by this issue as well.  I am on iOS 10.3.1, I am using a private GitHub repo with a 4096-bit key, not password, with default branch being `origin/master`.

When this issue occurs for me Pass for iOS will immediately crash if I force quit and relaunch.  If I reboot and launch it seems to just display a black screen.  Only option is to uninstall and reinstall but of course it just crashes again when I repeat the same setup.

**Comment by mssun** [comment]
I am solving this issue recently. I still cannot reproduce the issue on my
phone. Don't know why. I even asked a reporter for an account, but still
can clone the repo.

Now I'm am thinking there may be a problem with the released built.

If you have ability to built yourself, please do so. Then, report the crash
log here. Many thanks.

**Comment by nnutter** [comment]
Just wanted to share that the latest build on Test Flight (second build today) still crashes for me.

**Comment by mssun** [comment]
@nnutter Still cannot reproduce this issue. Can you provide some information?k Thanks.

**Comment by vonProteus** [comment]
i think this bug is fixed in 0.2.5 (21) at least for me

**Comment by steffen9000** [comment]
The bug is still present on the latest TestFlight build. I restored my phone through iTunes today and the very first thing I did was to install Pass via TestFlight - I get the exact same crash. 

I'll build my own version this weekend and hopefully send you some interesting crash reports. I *want* this bug report to be closed so you can release your great app to the App Store and fix the password manager situation on there. :)

**Comment by mssun** [comment]
@steffen9000 Any update? From the crash reports, I can see that those crashes are caused by ObjectiveGit. However, I don't know what kinds of input will trigger the crashes.

**Comment by mssun** [comment]
I add a check before the crash point, just a temporary work around.

Actually, this bug is caused by our upstream library, ObjectiveGit. I wish I could help to fix it but I can't reproduce the crash.

If you guys can give me an temporary test account, I would really appreciate.

**Comment by steffen9000** [comment]
The latest TestFlight build **works** on my iPhone again 😊

**Comment by yishilin14** [comment]
Happy to hear this! I am closing this issue now. Thank you for your patience. :-)

**Comment by nnutter** [comment]
It's working for me as well.  I look forward to being able to use Pass for iOS!  Thanks!
